### PR TITLE
Fixes strict dependency on django-reversion==1.4

### PR DESCRIPTION
**Pull request by jnovinger**
Replaces with `django-reversion>=1.4,<=1.7`

Have tested this manually and all seems to be okay. Will be in production shortly.

### CODE REVIEW

**Comment by Jbonnett** [comment]
@sergiosoria you did the most reversion stuff on our site, can you take a gander at this?

**Comment by sergiosoria** [comment]
@Jbonnett Yep. I'll take a look tonight.

**Comment by crccheck** [comment]
What changed to make the Travis CI build fail?

**Comment by Jbonnett** [comment]
The new revision requires django 1.5, it uses force_text, which is new in 1.5 
https://docs.djangoproject.com/en/dev/ref/utils/#django.utils.encoding.force_text

**Pull request closed without merging**
